### ISSUE TITLE
[Bug Report] [Mobile] Header: 'Search' field is not displayed after tapping 'Search' icon 

### ISSUE THREAD

**Issue by ElenSol** [ita-social-projects/dokazovi-requirements#410]
**Environment:** Android 7.0, Chrome 96.0.4664.45, Samsung Galaxy S7 edge
                            Android 10, Chrome 96.0.4664.45, Huawei P smart Z

**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/dokazovi-fe

**Resolution:** 

**Preconditions**
Main page of mobile version of site is opened

**Steps to reproduce**
1. Tap 'Search' icon on Header

**Actual result**
'Search' field is not displayed on Header while 'Доказові' logo disappeared, the user cann't neither search for required information nor scroll down the page 

**Expected result**
'Search' field is displayed on the Header while 'Доказові' logo disappeared, the user can search for required information in 'Search' field 

**Links**
[Test case #409 ]
[User story #203 ]
[Mock-up](https://user-images.githubusercontent.com/72273859/131229202-b304836d-d123-49ed-b775-5487942ff469.png)

**Attachments**
(https://user-images.githubusercontent.com/92861300/142920924-50dd04e0-5e58-4cf3-94f8-c482408fd812.png)

**Comment by besizzo** [comment]
Hello. Since I'm overwhelmed with tasks atm, I need to take put this one off. 

It's has somehow working solutions
branch bugfix410_revision_v4: search works but results shown without pagination or filters. Everything else works fine

branch bugfix410_revision_v3: unlike v4, this one works with pagination and filters, BUT it still bugs if you make a search query, and once you make another one - search results won't be correct and page keeps refreshing. I tried to fix it for a long time but didn't succeed.
